# Generated by Django 4.1.4 on 2023-01-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0003_alter_menuitem_category_alter_menuitem_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='inventory',
            field=models.CharField(max_length=255),
        ),
    ]
